# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
    
    # This vagrantfile builds a Windows Server 2022 box from https://github.com/gusztavvargadr/packer/
    config.vm.box = "gusztavvargadr/windows-server"
    
    # VirtualBox specific settings
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = 2 * 1024
        vb.cpus = 2
    end
    
    config.vm.provision "shell",
        inline: "New-Item -ItemType File -Path C:/winrmtest.txt"

end
